name: 3-Environments and Secrets

on:
workflow_dispatch:

permissions:
  contents: read 
  actions: read
  deployments: read
  
env:
 PROD_URL:  'https://github.com'
 DOCS_URL:  'https://docs.github.com'
 DEV_URL:  'https://docs.github.com/en/devlopers'
 
jobs:
 use-environment-dev:
   name: Use DEV environment
   run-on: ubuntu-latest
   
   
   environment:
    name: DEV
    url: ${{ env.DEV_URL }}
    
   steps:
    - run: echo "Run id = ${{ github.run_id }}"
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Step that uses the DEV environment
      run: echo "Deployment to ${{ env.URL1 }}..."
    
    - name: Echo env secret is redacted in the logs
      run: |
        echo Env secret is ${{ secrets.MY_ENV_SECRET }}
        echo ${{ secrets.MY_ENV_SECRET }} | sed 's/./& /g'
        
    use-environment-test:
    name: Use TEST environment
    runs-on: ubuntu-latest
    #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: use-environment-dev

    environment:
      name: TEST
      url: ${{ env.DOCS_URL }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Step that uses the TEST environment
        run: echo "Deployment to ${{ env.DOCS_URL }}..."
      
      # Secrets are redacted in the logs
      - name: Echo secrets are redacted in the logs
        run: |
          echo Repo secret is ${{ secrets.MY_REPO_SECRET }}
          echo Org secret is ${{ secrets.MY_ORG_SECRET }}
          echo Env secret is not accessible ${{ secrets.MY_ENV_SECRET }}
  use-environment-prod:
    name: Use PROD environment
    runs-on: ubuntu-latest
    #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    
    needs: use-environment-test

    environment:
      name: PROD
      url: ${{ env.PROD_URL }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Step that uses the PROD environment
        run: echo "Deployment to ${{ env.PROD_URL }}..."
        
      
      
      
      
      
      
      
      
